services:
  - type: web
    name: morix
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/ws_server.py
    plan: starter
    envVars:
      - key: PORT
        value: 5000
      - key: MORIX_DB
        value: morix.db
